### ISSUE TITLE
signed integer -1 parsing error

### ISSUE THREAD

**Issue by yongjunkimD** [jwhitbeck/java-rdb-parser#10]
hi ! 
I would like to inform you that while parsing dump.rdb file,  I found the method written below seems to have a problem in case of signed data.

`private byte[] readInteger8Bits() throws IOException {
  return String.valueOf(readByte()).getBytes(ASCII);
}`

`private int readByte() throws IOException {
  if (!buf.hasRemaining()) {
    fillBuffer();
  }
  return buf.get() & 0xff;
}`

The problem that I recognized was when I'm using this method, the figure -1 comes out wrong result 255 because the upfront bit cannot recognize it 'signed'.

To solve this problem, I think you should remove the '& 0xff' Operation Code in readByte method.

On top of that, I would like you to confirm whether readInteger16Bits, readInteger32Bits methods also have sames issues above.

I will be appreciated for your feedback as far as you can reach. :)

**Comment by jwhitbeck** [comment]
Hi @yongjunkimD 

Thanks for reporting this bug and pointing to the solution. I'll push a fix shortly.

**Comment by yongjunkimD** [comment]
@jwhitbeck
Thanks for reading my issue. i hope to slove the problem. :)

**Comment by jwhitbeck** [comment]
Fixed in v1.3.3. I hope it solves your problem.

**Comment by yongjunkimD** [comment]
Thanks !! I have confirmed your code. Have a nice day.
