### ISSUE TITLE
Report the bytes consumed

### ISSUE THREAD

**Issue by wangyeweikuer** [jwhitbeck/java-rdb-parser#11]
We use this tool to analyse RDB file and output the records to our Analytics Database, but we need to know how many bytes we scanned.

So can we add a new method to get the scanned bytes when parser called

**Comment by jwhitbeck** [comment]
Hi @wangyeweikuer 

What API do you need? If we add a `RdbParser.bytesRead()` method, what contract should that method have? 

More generally, would you mind telling me more about your use-case? I'm curious about why you need to know how many bytes have been scanned.

**Comment by wangyeweikuer** [comment]
> Hi @wangyeweikuer
> 
> What API do you need? If we add a `RdbParser.bytesRead()` method, what contract should that method have?
> 
> More generally, would you mind telling me more about your use-case? I'm curious about why you need to know how many bytes have been scanned.

Just as I said, we used this parser in our Analytics Database, developed by ourself, so we need such method for two causes: 1) show progress of some queries; 2) show scanned data bytes which we charge user fees according to

**Comment by jwhitbeck** [comment]
Thanks for explanation. I added a `bytesParsed()` method in 4ebe2f2ce1e38cb87577f24a5ebb51d959e588d2. Let me know if that addresses your needs.

**Comment by wangyeweikuer** [comment]
Thx very much. I will and should contribute some codes next time, LOL
