### ISSUE TITLE
Support Redis4.0 Binary Double 

### ISSUE THREAD

**Issue by jefferyship** [jwhitbeck/java-rdb-parser#3]
private KeyValuePair readEntry(byte[] ts, int valueType) throws IOException {
add:
case 5:
			return readSet2(ts, key);

// REDIS_RDB_TYPE_ZSET_2 = 5  # ZSET version 2 with doubles stored in binary.
	private KeyValuePair readSet2(byte[] ts, byte[] key) throws IOException {
		long len = readLength();
		if (len > Integer.MAX_VALUE) {
			throw new IllegalArgumentException("Sets with more than " + Integer.MAX_VALUE + " elements are not supported.");
		}
		int size = (int) len;
		List<byte[]> valueScoresPairs = new ArrayList<byte[]>(2 * size);
		for (int i = 0; i < size; ++i) {
			byte[] valueBuf = readStringEncoded2();
			valueScoresPairs.add(valueBuf);
			byte[] valueDBuf = readLongString();
			valueScoresPairs.add(valueDBuf);
		}
		return new KeyValuePair(ValueType.SET, ts, key, valueScoresPairs);
	}

private byte[] readLongString() throws IOException {
		return readBytes(8);
	}

 if (kvp.getValueType() == ValueType.SET) {
 // 2. zadd
	for (Iterator<byte[]> i = kvp.getValues().iterator(); i.hasNext();) {
		String uuid = str(i.next());
		long score = strLong(i.next());
		zadd(key, uuid, score, expTime);
	}
}

static long strLong(byte[] readBuffer) throws Exception {
	long value = (long) toDouble(readBuffer);
	return value;
}

public static double toDouble(byte[] bytes) {
	return ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).getDouble();
}

**Comment by jefferyship** [comment]
rdb.c

/* Saves a double for RDB 8 or greater, where IE754 binary64 format is assumed.
 * We just make sure the integer is always stored in little endian, otherwise
 * the value is copied verbatim from memory to disk.
 *
 * Return -1 on error, the size of the serialized value on success. */
int rdbSaveBinaryDoubleValue(rio *rdb, double val) {
    memrev64ifbe(&val);
    return rdbWriteRaw(rdb,&val,sizeof(val));
}

/* Loads a double from RDB 8 or greater. See rdbSaveBinaryDoubleValue() for
 * more info. On error -1 is returned, otherwise 0. */
int rdbLoadBinaryDoubleValue(rio *rdb, double *val) {
    if (rioRead(rdb,val,sizeof(*val)) == 0) return -1;
    memrev64ifbe(val);
    return 0;
}

**Comment by jefferyship** [comment]
* REDIS_RDB_TYPE_ZSET_2 = 5  # ZSET version 2 with doubles stored in binary.

**Comment by jefferyship** [comment]
private byte[] readDoubleBinaryString() throws IOException {
		return readBytes(8);
	}

**Comment by jwhitbeck** [comment]
@jefferyship It looks like you have already thought through how to support RDB 8. Would you mind opening a PR?

**Comment by jwhitbeck** [comment]
@jefferyship I was finally able to find some time to add support for RDB 8. The latest version (v1.3.0) incorporates all your suggestions.
