### ISSUE TITLE
How do I do it ? jedis.dump("name")

### ISSUE THREAD

**Issue by lwphk** [jwhitbeck/java-rdb-parser#6]
jedis.set("name","redis");
byte[] b = jedis.dump("name");
String name = parseDump("name")//How do I do it???

**Comment by jwhitbeck** [comment]
Hi @lwphk, I'm not sure how to help you. This seems like a [jedis](https://github.com/xetorthio/jedis) question, not a java-rdb-parser one.

**Comment by lwphk** [comment]
@jwhitbeck  Thank you for your answer.
This is my question
redis> SET message  hello
"OK"
redis> LPUSH name tom jack
"OK"
redis> DUMP message     //jedis.dump("message")
"\x00\x05hello\a\x00\x9c@\n\x85m\xfe\xf5\x10"
redis>
redis > dump name
"\x0e\x01\x16\x16\x00\x00\x00\x10\x00\x00\x00\x02\x00\x00\x04jack\x06\x03tom\xff\a\x00j\xa4\xbfX=SB)"
command  "dump", it has a few semantic characteristics. Values are encoded in the same format used by RDB.  I want to parse these keys , "message" and "name" 
I don't know how to start from your java-rdb-parser.

**Comment by jwhitbeck** [comment]
@lwphk, the first thing you need to do is create an RDB file.

```
127.0.0.1:6379> FLUSHALL
OK
127.0.0.1:6379> SET message hello
OK
127.0.0.1:6379>  LPUSH name tom jack
(integer) 2
127.0.0.1:6379> BGSAVE
Background saving started
127.0.0.1:6379> QUIT
```

This will create a `dump.rdb` file in the current working directory of the redis-server.

You can then parse this file using `java-rdb-parser`.

Copy the example code from the README to a Test.java file:

```java
import java.io.File;
import net.whitbeck.rdbparser.*;

public class Test {

  public static void printRdbFile(File file) throws Exception {
    try (RdbParser parser = new RdbParser(file)) {
      Entry e;
      while ((e = parser.readNext()) != null) {
        switch (e.getType()) {

        case DB_SELECT:
          System.out.println("Processing DB: " + ((DbSelect)e).getId());
          System.out.println("------------");
          break;

        case EOF:
          System.out.print("End of file. Checksum: ");
          for (byte b : ((Eof)e).getChecksum()) {
            System.out.print(String.format("%02x", b & 0xff));
          }
          System.out.println();
          System.out.println("------------");
          break;

        case KEY_VALUE_PAIR:
          System.out.println("Key value pair");
          KeyValuePair kvp = (KeyValuePair)e;
          System.out.println("Key: " + new String(kvp.getKey(), "ASCII"));
          if (kvp.hasExpiry()) {
            System.out.println("Expiry (ms): " + kvp.getExpiryMillis());
          }
          System.out.println("Value type: " + kvp.getValueType());
          System.out.print("Values: ");
          for (byte[] val : kvp.getValues()) {
            System.out.print(new String(val, "ASCII") + " ");
          }
          System.out.println();
          System.out.println("------------");
          break;
        }
      }
    }
  }

  public static void main(String[] args) throws Exception {
    printRdbFile(new File(args[0]));
  }
}
```

Compile it:

```
javac -cp ~/.m2/repository/net/whitbeck/rdb-parser/1.3.0/rdb-parser-1.3.0.jar Test.java 
```

Run it against the RDB dump file:

```
java -cp ~/.m2/repository/net/whitbeck/rdb-parser/1.3.0/rdb-parser-1.3.0.jar:. Test /path/to/dump.rdb 

Processing DB: 0
------------
Key value pair
Key: name
Value type: QUICKLIST
Values: jack tom 
------------
Key value pair
Key: message
Value type: VALUE
Values: hello 
------------
End of file. Checksum: ef0b5c1a1fec5bed
------------
```

Let me know if that helps.

**Comment by lwphk** [comment]
But I can't create a dump.rdb!  redis-server  Running on a remote server.

Distributed system
--------------------
service "shop"
Example ShopService.java
public class ShopService {

	public boolean createShopInCache(Shop shop) {
		Jedis jedis = new Jedis("67.22.134.23", 6379); //remote server.
		byte[] data = SerializeUtil.serialize(shop);
		String key = "in_redis_shop_"+shop.getId();
		String result = jedis.set(key.getBytes(), data);
		jedis.close();
		return "OK"==result;
	}
}
----------------------
service "shop-view"
Example ShopControlle.java
public class ShopController {

	@RequestMapping("/shop/detail")
	@ResponseBody
	public Shop shopDetail(@RequestParam(required=true)Integer shopId) {
		Jedis jedis = new Jedis("67.22.134.23", 6379);  // remote server.
		String key = "in_redis_shop_"+shopId;
		byte[] data = jedis.dump(key.getBytes()); //the data equals ==> service "shop" ShopService.java   byte[] data = SerializeUtil.serialize(shop);
		Shop shop = (Shop)SerializeUtil.unSerialize(data);
		return shop;
	}
}
I want to parse when the "shop-view" service is running!  How do I parse?

**Comment by jwhitbeck** [comment]
To be clear, this project is intended for parsing redis RDB files. However, it looks like you would like to store java objects in redis. I don't think `java-rdb-parser` is the tool for this purpose. 

In your case, I think that using `jedis.get` instead of `jedis.dump` would allow you to read back the raw bytes of your serialized java object.
