### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by spccold** [jwhitbeck/java-rdb-parser#7]
~~~java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at net.whitbeck.rdbparser.ZipList.get(ZipList.java:60)
	at net.whitbeck.rdbparser.QuickList.get(QuickList.java:30)
	at net.whitbeck.rdbparser.KeyValuePair.getValues(KeyValuePair.java:173)
	at RdbParserTest.main(RdbParserTest.java:30)
~~~

**Comment by jwhitbeck** [comment]
Hi,
Thanks for reporting this error. Could you please provide sample input for reproducing it?

**Comment by spccold** [comment]
my redis dump.rdb contains sensitive data, so i can't share it to you

**Comment by spccold** [comment]
![image](https://user-images.githubusercontent.com/8461826/41297584-08a32a94-6e92-11e8-9b86-1df47044de57.png)

![image](https://user-images.githubusercontent.com/8461826/41297511-db404b2c-6e91-11e8-8307-33e3127a7cf7.png)

**Comment by spccold** [comment]
https://github.com/sripathikrishnan/redis-rdb-tools  can parse this quicklist, so can you check the difference between java-rdb-parser and redis-rdb-tools?

**Comment by jwhitbeck** [comment]
I understand that you have sensitive data. If you know what list is triggering this issue in your data, then it would be extremely helpful to me if you could provide a toy example with fake data that triggers this bug.

**Comment by spccold** [comment]
@jwhitbeck this fix work for me, please hava a check, thank you
